# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 134, 316, 225))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ReadB = QtWidgets.QPushButton(self.layoutWidget)
        self.ReadB.setEnabled(False)
        self.ReadB.setObjectName("ReadB")
        self.horizontalLayout.addWidget(self.ReadB)
        self.comL = QtWidgets.QComboBox(self.layoutWidget)
        self.comL.setObjectName("comL")
        self.horizontalLayout.addWidget(self.comL)
        self.openB = QtWidgets.QPushButton(self.layoutWidget)
        self.openB.setObjectName("openB")
        self.horizontalLayout.addWidget(self.openB)
        self.closeB = QtWidgets.QPushButton(self.layoutWidget)
        self.closeB.setEnabled(False)
        self.closeB.setObjectName("closeB")
        self.horizontalLayout.addWidget(self.closeB)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.textBox = QtWidgets.QTextBrowser(self.layoutWidget)
        self.textBox.setObjectName("textBox")
        self.verticalLayout.addWidget(self.textBox)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(110, 40, 75, 23))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ReadB.setText(_translate("MainWindow", "READ"))
        self.openB.setText(_translate("MainWindow", "OPEN"))
        self.closeB.setText(_translate("MainWindow", "CLOSE"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
